import{useState}from'react';
type Kind='characters'|'items'|'spells'|'monsters';type Props={kind:Kind;onAppend:(s:string)=>void};
const labels={characters:'Character',items:'Item',spells:'Spell',monsters:'Monster'} as const;
const schemas:Record<Kind,{basic:[string,string][],details:[string,string][]}>={
characters:{basic:[['Name','text'],['Class','text'],['Level','number'],['Species','text'],['Background','text'],['Armor Class','number'],['Hit Points','number'],['Description','textarea']],details:[['Subclass','text'],['Speed','text'],['STR','number'],['DEX','number'],['CON','number'],['INT','number'],['WIS','number'],['CHA','number'],['Skills','text'],['Saving Throws','text'],['Features','textarea'],['Equipment','textarea'],['Spells','textarea'],['Biography','textarea']]},
items:{basic:[['Name','text'],['Type','select:Weapon|Armor|Wondrous Item|Potion|Scroll|Ring|Rod|Staff|Wand|Other'],['Rarity','select:Common|Uncommon|Rare|Very Rare|Legendary|Artifact|Other'],['Attunement','select:No|Yes'],['Effects','textarea'],['Description','textarea']],details:[['Damage / AC','text'],['Properties','text'],['Charges / Uses','text'],['Granted Spells','textarea']]},
spells:{basic:[['Name','text'],['Level','select:Cantrip|1|2|3|4|5|6|7|8|9'],['School','select:Abjuration|Conjuration|Divination|Enchantment|Evocation|Illusion|Necromancy|Transmutation'],['Casting Time','text'],['Range','text'],['Duration','text'],['Description','textarea']],details:[['Components','text'],['Material','text'],['Concentration','select:No|Yes'],['Ritual','select:No|Yes'],['Classes','text'],['Attack / Save','text'],['Damage / Healing','text'],['At Higher Levels','textarea']]},
monsters:{basic:[['Name','text'],['Size','text'],['Creature Type','text'],['Armor Class','text'],['Hit Points','text'],['Speed','text'],['Challenge / XP','text'],['Actions','textarea'],['Description','textarea']],details:[['Alignment','text'],['STR','number'],['DEX','number'],['CON','number'],['INT','number'],['WIS','number'],['CHA','number'],['Saving Throws','text'],['Skills','text'],['Resistances','text'],['Immunities','text'],['Senses','text'],['Languages','text'],['Traits','textarea'],['Reactions','textarea'],['Legendary / Mythic Actions','textarea'],['Spellcasting','textarea']]}
};
const Field=({name,type,value,onChange}:{name:string,type:string,value:string,onChange:(v:string)=>void})=><label className={type==='textarea'?'wide':''}><span>{name}</span>{type.startsWith('select:')?<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose…</option>{type.slice(7).split('|').map(o=><option key={o}>{o}</option>)}</select>:type==='textarea'?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={'Add '+name.toLowerCase()+'…'}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={name}/>}</label>;
export default function ContentBuilder({kind,onAppend}:Props){const schema=schemas[kind],all=[...schema.basic,...schema.details],blank=()=>Object.fromEntries(all.map(([n])=>[n,''])),[data,setData]=useState<Record<string,string>>(blank),[saved,setSaved]=useState<Record<string,string>[]>([]),[more,setMore]=useState(false);const title=data.Name||'Untitled '+labels[kind];const update=(n:string,v:string)=>setData(d=>({...d,[n]:v}));const text=[title,...all.filter(([n])=>data[n]&&n!=='Name').map(([n])=>n+': '+data[n])].join('\n\n');return <section className="contentBuilder simpleBuilder"><aside className="builderLibrary"><button className="newProject" onClick={()=>setData(blank())}>＋ New {labels[kind]}</button><h3>{labels[kind]} Library</h3>{saved.length?saved.map((x,i)=><button key={i} onClick={()=>setData(x)}>◆ {x.Name||'Untitled'}</button>):<p>No saved {kind} yet.</p>}</aside><div className="builderCenter"><div className="builderHead"><div><small>{labels[kind]} Builder</small><h1>{title}</h1><p className="builderIntro">Fill in the basics first. Extra details are optional.</p></div><div><button onClick={()=>setSaved(v=>[...v,{...data}])}>Save</button><button className="primary" onClick={()=>onAppend('\n'+text+'\n')}>Add to Book</button></div></div><h2 className="formSectionTitle">Basics</h2><div className="builderForm">{schema.basic.map(([n,t])=><Field key={n} name={n} type={t} value={data[n]||''} onChange={v=>update(n,v)}/>)}</div><button className="moreDetails" onClick={()=>setMore(v=>!v)}>{more?'− Hide extra details':'＋ Add more details (optional)'}</button>{more&&<><h2 className="formSectionTitle">Extra Details</h2><div className="builderForm">{schema.details.map(([n,t])=><Field key={n} name={n} type={t} value={data[n]||''} onChange={v=>update(n,v)}/>)}</div></>}</div><aside className="builderPreview"><h3>Book Preview</h3><article><h1>{title}</h1>{schema.basic.filter(([n])=>n!=='Name'&&data[n]).map(([n])=><p key={n}><b>{n}:</b> {data[n]}</p>)}</article><small>Preview shows the core information. Optional details are included when added to the book.</small></aside></section>}