import{useMemo,useState}from'react';import{consistencyIssues,encyclopedia,factionSource,findLoreLinks,loreTemplates,npcSource,playerSafeSource,timelineFromSource,type LoreVisibility}from'../source/loreStudio';
interface Props{source:string;onInsert:(s:string)=>void;onReplace:(s:string)=>void}
type Tab='templates'|'timeline'|'relations'|'npc'|'factions'|'wiki'|'visibility'|'book';
export default function LoreStudio({source,onInsert,onReplace}:Props){
 const[tab,setTab]=useState<Tab>('templates'),[name,setName]=useState(''),[detail,setDetail]=useState(''),[secret,setSecret]=useState(''),[visibility,setVisibility]=useState<LoreVisibility>('Player'),[query,setQuery]=useState('');
 const issues=useMemo(()=>consistencyIssues(source),[source]),links=useMemo(()=>findLoreLinks(source),[source]),events=useMemo(()=>timelineFromSource(source),[source]),entries=useMemo(()=>encyclopedia(source),[source]);
 const tabs:[Tab,string][]=[['templates','Templates'],['timeline','Timeline'],['relations','Links & Consistency'],['npc','NPC'],['factions','Faction / Religion'],['wiki','Encyclopedia'],['visibility','Player / GM'],['book','Book Builder']];
 return <section className="loreStudio"><div className="studioTitle"><div><b>Lore Studio</b><small>Worldbuilding tools that feed directly into your book.</small></div><span>{entries.length} lore entries</span></div><div className="studioTabs">{tabs.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div><div className="studioBody">
 {tab==='templates'&&<div className="templateGrid">{Object.entries(loreTemplates).map(([n,s])=><button key={n} onClick={()=>onInsert('\n'+s)}><b>{n}</b><small>Insert lore template</small></button>)}</div>}
 {tab==='timeline'&&<div><p className="studioHint">Timeline entries are detected from lore containing <b>Year / Age</b> or <b>Year:</b>.</p>{events.length?events.map(e=><div className="timelineRow" key={e.id}><b>{e.year}</b><span>{e.text}</span></div>):<p>No dated events yet.</p>}</div>}
 {tab==='relations'&&<div className="studioColumns"><div><h4>@ Lore Links</h4>{links.length?[...new Set(links)].map(x=><div className="wikiRow" key={x}>@{x}</div>):<p>Type @Name in lore to create a relationship.</p>}</div><div><h4>Consistency Check</h4>{issues.length?issues.map(x=><div className="issueRow" key={x}>⚠ {x}</div>):<p>✓ No simple consistency conflicts found.</p>}</div></div>}
 {tab==='npc'&&<div className="studioForm"><input placeholder="NPC name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Role / occupation" value={detail} onChange={e=>setDetail(e.target.value)}/><textarea placeholder="Secret" value={secret} onChange={e=>setSecret(e.target.value)}/><Visibility value={visibility} set={setVisibility}/><button className="primary" onClick={()=>onInsert(npcSource(name,detail,'',secret,visibility))}>Insert NPC Lore</button></div>}
 {tab==='factions'&&<div className="studioForm"><input placeholder="Faction or religion name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Purpose / central belief" value={detail} onChange={e=>setDetail(e.target.value)}/><Visibility value={visibility} set={setVisibility}/><div className="buttonPair"><button onClick={()=>onInsert(factionSource(name,'Faction',detail,visibility))}>Insert Faction</button><button onClick={()=>onInsert(factionSource(name,'Religion',detail,visibility))}>Insert Religion</button></div></div>}
 {tab==='wiki'&&<div><input className="wikiSearch" placeholder="Search world encyclopedia…" value={query} onChange={e=>setQuery(e.target.value)}/>{entries.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())).map(x=><div className="wikiRow" key={x.id}><b>{x.name}</b><small>{x.meta}</small></div>)}</div>}
 {tab==='visibility'&&<div><p className="studioHint">Entries marked <b>GM Only</b> or <b>Secret</b>, plus GM Truth sections, can be removed from a player copy.</p><button onClick={()=>onReplace(playerSafeSource(source))}>Create Player-Safe Source</button></div>}
 {tab==='book'&&<div><p className="studioHint">The encyclopedia below reflects your current top-level lore sections. Use page breaks to assemble them into a readable book.</p><div className="bookStats"><b>{entries.length}</b> sections <b>{events.length}</b> timeline events <b>{links.length}</b> lore links</div><button className="primary" onClick={()=>onReplace(source.replace(/\n(?=# )/g,'\n\\page\n'))}>Assemble Sections as Pages</button></div>}
 </div></section>
}
function Visibility({value,set}:{value:LoreVisibility;set:(v:LoreVisibility)=>void}){return <label className="visibility">Visibility <select value={value} onChange={e=>set(e.target.value as LoreVisibility)}><option>Player</option><option>GM Only</option><option>Secret</option></select></label>}
