import{useMemo,useState}from'react';import{consistencyIssues,encyclopedia,findLoreLinks,playerSafeSource,timelineFromSource,type LoreVisibility}from'../source/loreStudio';
interface Props{source:string;onInsert:(s:string)=>void;onReplace:(s:string)=>void}
type Tab='world'|'articles'|'timeline'|'atlas'|'relations'|'secrets';
const kinds=['Character','Settlement','Region','Faction','Religion','Deity','Creature','Item','Event','Culture','Organization','Location'] as const;
const categories=['World','People','Places','Factions','Faiths','History','Creatures','Items'];
const clean=(v:string)=>v.trim()||'—';
export default function LoreStudio({source,onInsert,onReplace}:Props){
 const[tab,setTab]=useState<Tab>('world'),[query,setQuery]=useState(''),[kind,setKind]=useState<(typeof kinds)[number]>('Location'),[name,setName]=useState('New Article'),[category,setCategory]=useState('World'),[summary,setSummary]=useState(''),[details,setDetails]=useState(''),[tags,setTags]=useState(''),[visibility,setVisibility]=useState<LoreVisibility>('Player'),[mapName,setMapName]=useState('World Map'),[pinName,setPinName]=useState('');
 const entries=useMemo(()=>encyclopedia(source),[source]),events=useMemo(()=>timelineFromSource(source),[source]),links=useMemo(()=>findLoreLinks(source),[source]),issues=useMemo(()=>consistencyIssues(source),[source]);
 const filtered=entries.filter(x=>(x.name+' '+x.meta).toLowerCase().includes(query.toLowerCase()));
 const articleSource=()=>`\n# ${clean(name)}\n*${kind} · ${category}*\n\n**Visibility:** ${visibility}  \n**Tags:** ${clean(tags)}\n\n## Overview\n${clean(summary)}\n\n## Details\n${clean(details)}\n\n## Connections\nAdd @Article links to related people, places, factions, events, or items.\n`;
 const tabs:[Tab,string][]=[['world','World Library'],['articles','Articles'],['timeline','Timeline'],['atlas','Atlas'],['relations','Relations'],['secrets','GM Secrets']];
 return <section className="worldCreator">
  <div className="worldCreatorTop"><div><b>World Creator</b><small>Wiki-style worldbuilding + Homebrewery book source</small></div><div className="worldStats"><span><b>{entries.length}</b> Articles</span><span><b>{events.length}</b> Events</span><span><b>{new Set(links).size}</b> Links</span></div></div>
  <div className="worldCreatorTabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  <div className="worldCreatorBody">
   {tab==='world'&&<div className="worldManager"><aside><button className="newArticle" onClick={()=>setTab('articles')}>＋ New Article</button><input placeholder="Search world…" value={query} onChange={e=>setQuery(e.target.value)}/><h4>WORLD TREE</h4>{categories.map(c=><button key={c} onClick={()=>{setCategory(c);setTab('articles')}}>▸ {c}</button>)}</aside><div className="worldLibrary"><div className="libraryHead"><div><h3>{category}</h3><small>Your setting encyclopedia. Articles remain book-ready source.</small></div><button onClick={()=>setTab('articles')}>Create in {category}</button></div>{filtered.length?<div className="articleCards">{filtered.map(x=><article key={x.id}><b>{x.name}</b><small>{x.meta||'Lore article'}</small><span>Open in Homebrewery source →</span></article>)}</div>:<div className="emptyLibrary"><b>No matching articles yet.</b><span>Create an article or write a # top-level section in Homebrewery source.</span></div>}</div></div>}
   {tab==='articles'&&<div className="articleEditor"><div className="articleForm"><div className="articleFormHead"><div><b>Create World Article</b><small>Structured lore that becomes Homebrewery-compatible Markdown.</small></div><Visibility value={visibility} set={setVisibility}/></div><div className="articleFields"><label>Article Type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{kinds.map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Title<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="wide">Summary<textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="What should a reader know first?"/></label><label className="wide">Lore / Details<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="History, appearance, culture, motives, rules, rumors…"/></label><label className="wide">Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="empire, capital, military"/></label></div><div className="articleActions"><button onClick={()=>{setName('New Article');setSummary('');setDetails('');setTags('')}}>Clear</button><button className="primary" onClick={()=>onInsert(articleSource())}>Add to World & Source</button></div></div><div className="articlePreview"><small>BOOK SOURCE PREVIEW</small><pre>{articleSource()}</pre></div></div>}
   {tab==='timeline'&&<div className="timelineWorkspace"><div className="timelineToolbar"><div><h3>World Timeline</h3><small>Dated lore is collected automatically from your source.</small></div><button onClick={()=>onInsert('\n# New Historical Event\n*Event · History*\n\n**Year:** 0\n\n## Overview\nDescribe the event.\n')}>＋ Event</button></div>{events.length?events.map(e=><div className="timelineEvent" key={e.id}><b>{e.year}</b><span>{e.text}</span></div>):<div className="emptyLibrary">No dated events yet. Add <b>Year:</b> to an event article.</div>}</div>}
   {tab==='atlas'&&<div className="atlasWorkspace"><div className="atlasCanvas"><div className="mapPlaceholder"><b>{mapName}</b><span>Map workspace</span><small>Import artwork through the page/image tools, then document locations here as linked lore articles.</small></div></div><aside><h3>Atlas</h3><label>Map Name<input value={mapName} onChange={e=>setMapName(e.target.value)}/></label><label>New Pin / Location<input value={pinName} onChange={e=>setPinName(e.target.value)}/></label><button className="primary" onClick={()=>{if(pinName.trim()){onInsert(`\n# ${pinName.trim()}\n*Location · Places*\n\n## Overview\nMap location on ${mapName}.\n`);setPinName('')}}}>Create Linked Location</button><p>Locations created here become wiki articles and remain available to the book source.</p></aside></div>}
   {tab==='relations'&&<div className="relationsWorkspace"><div><h3>Linked Lore</h3><p>Use <b>@Name</b> anywhere in your lore to connect articles.</p>{[...new Set(links)].map(x=><div className="relationRow" key={x}>@{x}</div>)}{!links.length&&<small>No @ links yet.</small>}</div><div><h3>Consistency Check</h3>{issues.length?issues.map(x=><div className="issueRow" key={x}>⚠ {x}</div>):<div className="relationGood">✓ No simple conflicts detected.</div>}</div></div>}
   {tab==='secrets'&&<div className="secretWorkspace"><div><h3>Player / GM Visibility</h3><p>Keep one master source. Articles marked <b>GM Only</b> or <b>Secret</b> can be stripped from a player-facing copy.</p><div className="visibilityLegend"><span>◉ Player</span><span>◆ GM Only</span><span>● Secret</span></div></div><button className="primary" onClick={()=>onReplace(playerSafeSource(source))}>Create Player-Safe Source</button></div>}
  </div>
 </section>
}
function Visibility({value,set}:{value:LoreVisibility;set:(v:LoreVisibility)=>void}){return <label className="visibility">Visibility <select value={value} onChange={e=>set(e.target.value as LoreVisibility)}><option>Player</option><option>GM Only</option><option>Secret</option></select></label>}
