import{useEffect,useState}from'react';import{clampStamp,createStampPlacement,stampAssets,type StampAsset,type StampPlacement}from'../source/stampAssets';
interface Target{id:string;name:string;src:string}
interface Props{onApply:(asset:StampAsset,placement:StampPlacement,targetId:string)=>void;targets?:Target[]}
export default function StampStudio({onApply,targets=[]}:Props){
 const[selected,setSelected]=useState(stampAssets[0]),[p,setP]=useState(()=>createStampPlacement(stampAssets[0].id)),[tab,setTab]=useState<'Stamps & Seals'|'Page Effects'|'Decorative'>('Stamps & Seals'),[targetId,setTargetId]=useState('');
 useEffect(()=>{if(!targets.some(x=>x.id===targetId))setTargetId(targets[0]?.id||'')},[targets,targetId]);
 const target=targets.find(x=>x.id===targetId),set=(patch:Partial<StampPlacement>)=>setP(v=>clampStamp({...v,...patch}));
 return <section className="stampStudio"><div className="stampHeader"><div><b>Stamps & Page Effects</b><small>Choose artwork, select an effect, preview it, then apply.</small></div><button className="primary" disabled={!target} onClick={()=>target&&onApply(selected,p,target.id)}>Apply to Selected Image</button></div>
 <div className="stampTarget"><label>Artwork Target <select value={targetId} onChange={e=>setTargetId(e.target.value)} disabled={!targets.length}>{targets.length?targets.map(x=><option key={x.id} value={x.id}>{x.name}</option>):<option>No artwork on this page</option>}</select></label>{!targets.length&&<p>Add artwork to the current book page first, then return to Stamps.</p>}</div>
 <div className="stampTabs">{(['Stamps & Seals','Page Effects','Decorative'] as const).map(x=><button type="button" key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
 <div className="stampLayout"><div className="stampGrid">{stampAssets.filter(x=>x.category===tab).map(a=><button type="button" key={a.id} className={selected.id===a.id?'selected':''} onClick={()=>{setSelected(a);set({assetId:a.id})}}><span>{a.glyph}</span><small>{a.name}</small></button>)}</div><div className="stampPreview"><div className="stampPreviewPaper">{target?<img src={target.src} alt={target.name}/>:<div className="stampEmptyPreview">No artwork selected</div>}<span className={'stampDemo '+p.layer} style={{fontSize:p.size/2,opacity:p.opacity,transform:`translate(-50%,-50%) rotate(${p.rotation}deg)`,left:p.x+'%',top:p.y+'%'}}>{selected.glyph}</span></div><div className="stampControls"><label>Size <input type="range" min="24" max="400" value={p.size} onChange={e=>set({size:Number(e.target.value)})}/><em>{p.size}px</em></label><label>Opacity <input type="range" min="5" max="100" value={p.opacity*100} onChange={e=>set({opacity:Number(e.target.value)/100})}/><em>{Math.round(p.opacity*100)}%</em></label><label>Rotation <input type="range" min="-180" max="180" value={p.rotation} onChange={e=>set({rotation:Number(e.target.value)})}/><em>{p.rotation}°</em></label><label>X <input type="range" min="0" max="100" value={p.x} onChange={e=>set({x:Number(e.target.value)})}/></label><label>Y <input type="range" min="0" max="100" value={p.y} onChange={e=>set({y:Number(e.target.value)})}/></label><label>Layer <select value={p.layer} onChange={e=>set({layer:e.target.value as 'front'|'back'})}><option value="front">Bring to Front</option><option value="back">Send to Back</option></select></label></div></div></div></section>
}