const MODULE_ID="rpg-book-builder-companion";
const STEPS=["Rules & Source","Species","Background","Class","Subclass","Ability Scores","Feats & Options","Spells","Equipment","Character Details","Review","Submit to GM"];
const CONTENT=[["spell","Spell Book"],["equipment","Equipment & Items"],["feat","Feats"],["species","Species"],["class","Classes"],["background","Backgrounds"]];
Hooks.once("ready",()=>{const mod=game.modules.get(MODULE_ID);if(mod)mod.api={...(mod.api||{}),openCharacterCreator};});
Hooks.on("renderActorDirectory",(_app,html)=>{const root=html instanceof HTMLElement?html:html?.[0];if(!root||root.querySelector("[data-rpgbb-creator]"))return;const host=root.querySelector(".directory-header .header-actions, .directory-header");if(!host)return;const b=document.createElement("button");b.type="button";b.dataset.rpgbbCreator="";b.className="rpgbb-character-creator";b.innerHTML='<i class="fas fa-dice-d20"></i> Character Creator';b.onclick=()=>openCharacterCreator();host.append(b);});
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function ownedCharacters(){return game.actors.filter(a=>a.type==="character"&&(game.user.isGM||a.isOwner))}
async function openCharacterCreator(){
 const actors=ownedCharacters();if(!actors.length){ui.notifications.warn("Create or assign a D&D5e character Actor first.");return}
 let state={actorId:actors[0].id,rulesVersion:"2024",step:1,kind:"species",query:"",catalog:[],loadToken:0};
 const shell=()=>`<div class="rpgbb-creator-shell">
 <header class="rpgbb-creator-top"><b>Character Creator</b><div class="rpgbb-rule-toggle"><button data-rules="2014" class="${state.rulesVersion==="2014"?"active":""}">D&D 5e · 2014 SRD 5.1</button><button data-rules="2024" class="${state.rulesVersion==="2024"?"active":""}">D&D 5e · 2024 SRD 5.2.1</button></div><select data-actor>${actors.map(a=>`<option value="${a.id}" ${a.id===state.actorId?"selected":""}>${esc(a.name)}</option>`).join("")}</select></header>
 <div class="rpgbb-creator-grid"><nav class="rpgbb-steps">${STEPS.map((s,i)=>`<button data-step="${i+1}" class="${state.step===i+1?"active":""}"><span>${i+1}</span>${s}</button>`).join("")}<h4>Content</h4>${CONTENT.map(([k,n])=>`<button data-kind="${k}" class="${state.kind===k?"content-active":""}"><i class="fas fa-book"></i>${n}</button>`).join("")}</nav>
 <main class="rpgbb-catalog"><div class="rpgbb-catalog-head"><div><small>SRD + Homebrew</small><h2>${CONTENT.find(x=>x[0]===state.kind)?.[1]||"Content"}</h2></div><div class="rpgbb-catalog-tools"><button data-homebrew><i class="fas fa-hammer"></i> Quick Homebrew</button><input data-search placeholder="Search ${state.kind}..." value="${esc(state.query)}"></div></div><div data-results class="rpgbb-card-grid"><p class="hint">Loading Foundry D&D5e compendiums…</p></div></main>
 <aside class="rpgbb-sheet-preview" data-preview></aside></div></div>`;
 const dialog=new foundry.applications.api.DialogV2({window:{title:"RPG Book Builder · D&D5e Character Creator",resizable:true},position:{width:1380,height:820},content:shell(),buttons:[{action:"close",label:"Close"}],render:(_e,d)=>wire(d)});
 dialog.render(true);
 async function wire(d){const el=d.element;const refreshPreview=()=>{const a=game.actors.get(state.actorId);el.querySelector("[data-preview]").innerHTML=`<h3>Character Preview</h3><div class="rpgbb-portrait"><img src="${a?.img||"icons/svg/mystery-man.svg"}"><div><b>${esc(a?.name||"Character")}</b><small>D&D ${state.rulesVersion}</small></div></div><button data-sheet>Open D&D5e Sheet</button><hr><h4>Quick Add</h4><p>Choose SRD content on the left to add it directly to this native Foundry character sheet.</p>`;el.querySelector("[data-sheet]").onclick=()=>a?.sheet?.render(true)};
  const load=async()=>{const api=game.modules.get(MODULE_ID)?.api;if(!api?.getSrdCatalog){ui.notifications.error("SRD catalog is not ready.");return}const token=++state.loadToken;const rulesVersion=state.rulesVersion,kind=state.kind,query=state.query;let results;try{results=await api.getSrdCatalog({rulesVersion,kind,query})}catch(e){console.error(MODULE_ID,e);ui.notifications.error(e?.message||"Could not load SRD content.");return}if(token!==state.loadToken||rulesVersion!==state.rulesVersion||kind!==state.kind||query!==state.query)return;state.catalog=results;const box=el.querySelector("[data-results]");box.innerHTML=results.length?results.map((x,i)=>`<article class="rpgbb-content-card"><div><b>${esc(x.name)}</b><small>${esc(x.type)} · ${esc(x.pack)}</small></div><button data-add="${i}"><i class="fas fa-plus"></i> Add</button></article>`).join(""):'<p class="hint">No matching SRD content found in the installed D&D5e compendiums.</p>';box.querySelectorAll("[data-add]").forEach(b=>b.onclick=async()=>{const a=game.actors.get(state.actorId),x=state.catalog[Number(b.dataset.add)];if(b.disabled)return;b.disabled=true;try{await api.addSrdDocumentToActor(a,x.uuid);ui.notifications.info(`${x.name} added to ${a.name}.`)}catch(e){ui.notifications.error(e?.message||"Could not add content.")}finally{b.disabled=false}})};
  el.querySelectorAll("[data-rules]").forEach(b=>b.onclick=async()=>{state.rulesVersion=b.dataset.rules;el.querySelectorAll("[data-rules]").forEach(x=>x.classList.toggle("active",x.dataset.rules===state.rulesVersion));refreshPreview();await load()});
  el.querySelector("[data-actor]").onchange=e=>{state.actorId=e.target.value;refreshPreview()};el.querySelector("[data-homebrew]").onclick=()=>openQuickHomebrew(state.kind);
  el.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>{state.step=Number(b.dataset.step);el.querySelectorAll("[data-step]").forEach(x=>x.classList.toggle("active",Number(x.dataset.step)===state.step));const map={2:"species",3:"background",4:"class",5:"subclass",7:"feat",8:"spell",9:"equipment"};if(map[state.step]){state.kind=map[state.step];el.querySelectorAll("[data-kind]").forEach(x=>x.classList.toggle("content-active",x.dataset.kind===state.kind));load()}});
  el.querySelectorAll("[data-kind]").forEach(b=>b.onclick=()=>{state.kind=b.dataset.kind;el.querySelectorAll("[data-kind]").forEach(x=>x.classList.toggle("content-active",x.dataset.kind===state.kind));load()});
  let timer;el.querySelector("[data-search]").oninput=e=>{state.query=e.target.value;clearTimeout(timer);timer=setTimeout(load,180)};
  refreshPreview();await load();
 }}
async function openQuickHomebrew(kind="spell"){const api=game.modules.get(MODULE_ID)?.api;if(!api?.openPlayerContentBuilder){ui.notifications.warn("Homebrew approval tools are not ready.");return}const supported=kind==="species"?"species":kind==="spell"?"spell":"item";await game.settings.set(MODULE_ID,"contentDraft",{type:supported,name:"",description:"",submissionId:""});return api.openPlayerContentBuilder()}
export{openCharacterCreator,openQuickHomebrew};
