import type{LoreEntry,LoreKind,LoreVisibility}from'./loreStudio';
export interface FoundryLoreEntry extends LoreEntry{dnd5e?:{fields:Record<string,string>;sections:Record<string,{name:string;text:string}[]>}}
export interface FoundryExportPackage{format:'rpg-book-builder-foundry';version:1;title:string;createdAt:string;entries:FoundryLoreEntry[]}
const kinds=new Set<LoreKind>(['Empire','Settlement','Person','Faction','Religion','History','Item','Creature','Mystery']);
function meta(line=''){const m=line.match(/\*([^*]+)\*/);if(!m)return{kind:'History' as LoreKind,visibility:'Player' as LoreVisibility};const parts=m[1].split('·').map(x=>x.trim());const kind=(kinds.has(parts[0] as LoreKind)?parts[0]:'History')as LoreKind;const visibility=(['Player','GM Only','Secret'].includes(parts.at(-1)||'')?parts.at(-1):'Player')as LoreVisibility;return{kind,visibility}}
export function loreEntriesFromSource(source:string):FoundryLoreEntry[]{const heads=[...source.matchAll(/^# ([^\n]+)$/gm)];return heads.map((h,i)=>{const start=h.index!+h[0].length,end=i+1<heads.length?heads[i+1].index!:source.length,raw=source.slice(start,end).trim(),first=raw.split('\n')[0]||'',m=meta(first),body=raw.replace(/^\*[^\n]+\*\s*/,'').trim();return{id:`lore-${i}-${h[1].trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`,name:h[1].trim(),kind:m.kind,visibility:m.visibility,body,links:findLinks(body),dnd5e:dnd5eData(body)}})}
function dnd5eData(body:string){const fields:Record<string,string>={};for(const m of body.matchAll(/^\*\*([^*]+)\*\*\s*:?\s*([^\n]+)$/gm))fields[m[1].trim()]=m[2].trim();const sections:Record<string,{name:string;text:string}[]>={};let current='';for(const line of body.split('\n')){const h=line.match(/^##+\s+(.+)/);if(h){current=h[1].trim();sections[current]??=[];continue}const e=line.match(/^\*\*([^*]+)\*\*\s*\.?\s*(.*)$/);if(current&&e)sections[current].push({name:e[1].trim(),text:e[2].trim()})}return{fields,sections}}
function findLinks(body:string){return[...body.matchAll(/@([A-Za-z][A-Za-z0-9 '\-]{0,60}?)(?=\s+@|[.,;:!?)]|$)/g)].map(x=>x[1].trim().replace(/\s+(?:and|or|but)$/i,'').trim())}
export function createFoundryPackage(title:string,source:string):FoundryExportPackage{return{format:'rpg-book-builder-foundry',version:1,title:title||'RPG Book Builder',createdAt:new Date().toISOString(),entries:loreEntriesFromSource(source)}}
export function foundryFilename(title:string){const safe=(title||'campaign').trim().replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'campaign';return safe+'.rpgfoundry'}
export function downloadFoundryPackage(pkg:FoundryExportPackage){const blob=new Blob([JSON.stringify(pkg,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=foundryFilename(pkg.title);a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
