import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{BookOpen,Download,FilePlus2,Image as ImageIcon,Plus,Redo2,Save,Trash2,Undo2,Upload}from'lucide-react';import'./styles.css';

type Kind='text'|'image'|'statblock';
type Block={id:string;kind:Kind;title:string;body:string;image?:string};
type Page={id:string;blocks:Block[]};
type Project={title:string;pages:Page[];activePage:string};
const uid=()=>crypto.randomUUID();
const starter=():Project=>{const p=uid();return{title:'Untitled Adventure',activePage:p,pages:[{id:p,blocks:[{id:uid(),kind:'text',title:'Chapter One',body:'Begin writing your adventure here. Click any text to edit it directly.'}]}]}};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
function App(){
 const[project,setProject]=useState<Project>(()=>{try{return JSON.parse(localStorage.getItem('rpg-book-builder')||'null')||starter()}catch{return starter()}});
 const[history,setHistory]=useState<Project[]>([]),[future,setFuture]=useState<Project[]>([]),fileRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLInputElement>(null);
 const page=project.pages.find(p=>p.id===project.activePage)||project.pages[0];
 useEffect(()=>localStorage.setItem('rpg-book-builder',JSON.stringify(project)),[project]);
 const commit=(fn:(p:Project)=>void)=>{setHistory(h=>[...h.slice(-49),clone(project)]);setFuture([]);setProject(p=>{const n=clone(p);fn(n);return n})};
 const update=(id:string,patch:Partial<Block>)=>commit(p=>Object.assign(p.pages.find(x=>x.id===p.activePage)!.blocks.find(x=>x.id===id)!,patch));
 const add=(kind:Kind)=>commit(p=>p.pages.find(x=>x.id===p.activePage)!.blocks.push({id:uid(),kind,title:kind==='statblock'?'New Creature':kind==='image'?'Artwork':'New Section',body:kind==='statblock'?'Medium creature, unaligned\nArmor Class 15\nHit Points 45\nSpeed 30 ft.\n\nActions\nAdd attacks, abilities, traits, and rules here.':'Start writing…'}));
 const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[clone(project),...f]);setHistory(h=>h.slice(0,-1));setProject(prev)};
 const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,clone(project)]);setFuture(f=>f.slice(1));setProject(next)};
 const save=()=>{const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(project.title||'rpg-book')+'.rpgbook';a.click();URL.revokeObjectURL(a.href)};
 const load=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(!x.pages?.length)throw 0;setHistory([]);setFuture([]);setProject(x)}catch{alert('That project file could not be opened.')}};r.readAsText(f)};
 const image=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>commit(p=>p.pages.find(x=>x.id===p.activePage)!.blocks.push({id:uid(),kind:'image',title:f.name,body:'',image:String(r.result)}));r.readAsDataURL(f)};
 return <div className="app"><header><b><BookOpen/> RPG Book Builder</b><input className="projectTitle" value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/><nav><button title="Undo" disabled={!history.length} onClick={undo}><Undo2/></button><button title="Redo" disabled={!future.length} onClick={redo}><Redo2/></button><button onClick={save}><Save/> Save</button><button onClick={()=>fileRef.current?.click()}><Upload/> Open</button><button className="primary" onClick={()=>window.print()}><Download/> Export PDF</button></nav></header>
 <aside className="pages"><h3>Pages</h3>{project.pages.map((p,i)=><button key={p.id} className={'thumb '+(p.id===project.activePage?'selected':'')} onClick={()=>setProject({...project,activePage:p.id})}><span>Page {i+1}</span><small>{p.blocks.length} blocks</small></button>)}<button onClick={()=>commit(p=>{const id=uid();p.pages.push({id,blocks:[]});p.activePage=id})}><Plus/> Add page</button>{project.pages.length>1&&<button className="danger" onClick={()=>commit(p=>{p.pages=p.pages.filter(x=>x.id!==p.activePage);p.activePage=p.pages[0].id})}><Trash2/> Delete page</button>}</aside>
 <main><div className="paper" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();image(e.dataTransfer.files[0])}}><div className="pageTitle">RPG BOOK BUILDER</div>{page.blocks.length===0&&<div className="empty">Add text, artwork, or a statblock from the right panel.</div>}{page.blocks.map(b=><article className={'block '+b.kind} key={b.id}>{b.kind==='image'?(b.image?<img src={b.image} alt={b.title}/>:<div className="imageDrop"><ImageIcon/> Drop artwork here</div>):<><input className="blockTitle" value={b.title} onChange={e=>update(b.id,{title:e.target.value})}/><textarea value={b.body} onChange={e=>update(b.id,{body:e.target.value})}/></>}<button className="remove" title="Remove block" onClick={()=>commit(p=>{const q=p.pages.find(x=>x.id===p.activePage)!;q.blocks=q.blocks.filter(x=>x.id!==b.id)})}><Trash2/></button></article>)}</div></main>
 <aside className="tools"><h3>Insert</h3><button onClick={()=>add('text')}>Text block</button><button onClick={()=>imageRef.current?.click()}>Artwork</button><button onClick={()=>add('statblock')}>Monster / NPC</button><h3>Templates</h3>{['Spell','Item','Vehicle','Trap','Encounter','Custom'].map(x=><button key={x} onClick={()=>{add('statblock')}}>{x}</button>)}<p className="hint">Projects autosave locally. Save creates a portable .rpgbook file. Export PDF opens your system print dialog; choose “Save as PDF”.</p></aside>
 <input hidden ref={fileRef} type="file" accept=".rpgbook,.json" onChange={e=>load(e.target.files?.[0])}/><input hidden ref={imageRef} type="file" accept="image/*" onChange={e=>image(e.target.files?.[0])}/></div>}
createRoot(document.getElementById('root')!).render(<App/>);