import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowDown,ArrowUp,BookOpen,Copy,Download,Image as ImageIcon,Plus,Redo2,Save,Trash2,Undo2,Upload}from'lucide-react';import'./styles.css';
import type{DocumentBlock,Project,StatblockKind}from'./model/types';import{activePage,cloneProject,createImageBlock,createPage,createProject,createStatblock,createTextBlock}from'./model/project';import{commit as commitHistory,createHistory,redo as redoHistory,undo as undoHistory,type HistoryState}from'./model/history';import{autosave,loadAutosave,parseProject,serializeProject}from'./storage/projectStorage';

function migrateLegacy():Project|null{try{const raw=localStorage.getItem('rpg-book-builder');if(!raw)return null;const old=JSON.parse(raw);if(!Array.isArray(old.pages)||!old.pages.length)return null;const p=createProject();p.title=old.title||p.title;p.pages=old.pages.map((page:any,i:number)=>({id:page.id||crypto.randomUUID(),name:`Page ${i+1}`,blocks:(page.blocks||[]).map((b:any):DocumentBlock=>b.kind==='image'?createImageBlock(b.image||'',b.title||'Artwork'):b.kind==='statblock'?{...createStatblock('custom'),id:b.id||crypto.randomUUID(),title:b.title||'New Creature',body:b.body||''}:{...createTextBlock(),id:b.id||crypto.randomUUID(),title:b.title||'New Section',body:b.body||''})}));p.activePageId=old.activePage&&p.pages.some(x=>x.id===old.activePage)?old.activePage:p.pages[0].id;return p}catch{return null}}
function App(){
 const[history,setHistory]=useState<HistoryState>(()=>createHistory(loadAutosave()??migrateLegacy()??createProject()));const[drafts,setDrafts]=useState<Record<string,string>>({});const project=history.present;const fileRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLInputElement>(null);const page=activePage(project);
 useEffect(()=>autosave(project),[project]);
 const change=(fn:(p:Project)=>void)=>setHistory(h=>{const n=cloneProject(h.present);fn(n);n.updatedAt=new Date().toISOString();return commitHistory(h,n)});
 const replaceBlock=(id:string,patch:Partial<DocumentBlock>)=>change(p=>{const b=activePage(p).blocks.find(x=>x.id===id);if(b)Object.assign(b,patch)});
 const draftKey=(id:string,field:'title'|'body')=>id+':'+field;
 const draft=(id:string,field:'title'|'body',value:string)=>setDrafts(d=>({...d,[draftKey(id,field)]:value}));
 const finishDraft=(id:string,field:'title'|'body',original:string)=>{const key=draftKey(id,field),value=drafts[key];if(value!==undefined&&value!==original)replaceBlock(id,{[field]:value} as Partial<DocumentBlock>);setDrafts(d=>{const n={...d};delete n[key];return n})};
 const addStat=(template:StatblockKind)=>change(p=>activePage(p).blocks.push(createStatblock(template)));
 const addTextStyle=(style:'body'|'heading'|'note'|'table')=>change(p=>{const b=createTextBlock();b.style=style;b.title=style==='heading'?'Section Heading':style==='note'?'GM Note':style==='table'?'Table':'New Section';b.body=style==='table'?'Name | Value\n--- | ---\nEntry | Detail':style==='note'?'Add an important note, rule, or sidebar here.':'Start writing…';activePage(p).blocks.push(b)});
 const moveBlock=(id:string,delta:number)=>change(p=>{const q=activePage(p),i=q.blocks.findIndex(x=>x.id===id),j=i+delta;if(i<0||j<0||j>=q.blocks.length)return;[q.blocks[i],q.blocks[j]]=[q.blocks[j],q.blocks[i]]});
 const movePage=(delta:number)=>change(p=>{const i=p.pages.findIndex(x=>x.id===p.activePageId),j=i+delta;if(i<0||j<0||j>=p.pages.length)return;[p.pages[i],p.pages[j]]=[p.pages[j],p.pages[i]]});
 const duplicatePage=()=>change(p=>{const i=p.pages.findIndex(x=>x.id===p.activePageId),copy=structuredClone(p.pages[i]);copy.id=crypto.randomUUID();copy.name=copy.name+' Copy';copy.blocks=copy.blocks.map(b=>({...b,id:crypto.randomUUID()}));p.pages.splice(i+1,0,copy);p.activePageId=copy.id});
 const undo=()=>setHistory(undoHistory),redo=()=>setHistory(redoHistory);
 const save=()=>{const blob=new Blob([serializeProject(project)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(project.title.trim()||'rpg-book')+'.rpgbook';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const load=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=parseProject(String(r.result));setHistory(createHistory(p))}catch{alert('That project file is damaged or uses an unsupported format.')}};r.readAsText(f)};
 const image=(f?:File)=>{if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>change(p=>activePage(p).blocks.push(createImageBlock(String(r.result),f.name)));r.readAsDataURL(f)};
 return <div className="app"><header><b><BookOpen/> RPG Book Builder</b><input className="projectTitle" value={project.title} onChange={e=>change(p=>{p.title=e.target.value})}/><nav><button title="Undo" disabled={!history.past.length} onClick={undo}><Undo2/></button><button title="Redo" disabled={!history.future.length} onClick={redo}><Redo2/></button><button onClick={save}><Save/> Save</button><button onClick={()=>fileRef.current?.click()}><Upload/> Open</button><button className="primary" onClick={()=>window.print()}><Download/> Export PDF</button></nav></header>
 <aside className="pages"><h3>Pages</h3><input className="pageName" value={page.name} onChange={e=>change(p=>{activePage(p).name=e.target.value})}/><div className="pageActions"><button title="Move page up" disabled={project.pages[0].id===page.id} onClick={()=>movePage(-1)}><ArrowUp/></button><button title="Move page down" disabled={project.pages.at(-1)?.id===page.id} onClick={()=>movePage(1)}><ArrowDown/></button><button title="Duplicate page" onClick={duplicatePage}><Copy/></button></div>{project.pages.map((p,i)=><button key={p.id} className={'thumb '+(p.id===project.activePageId?'selected':'')} onClick={()=>change(x=>{x.activePageId=p.id})}><span>{p.name||`Page ${i+1}`}</span><small>{p.blocks.length} blocks</small></button>)}<button onClick={()=>change(p=>{const q=createPage(`Page ${p.pages.length+1}`);p.pages.push(q);p.activePageId=q.id})}><Plus/> Add page</button>{project.pages.length>1&&<button className="danger" onClick={()=>change(p=>{p.pages=p.pages.filter(x=>x.id!==p.activePageId);p.activePageId=p.pages[0].id})}><Trash2/> Delete page</button>}</aside>
 <main><div className={'paper '+project.settings.pageSize} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();image(e.dataTransfer.files[0])}}><div className="pageTitle">RPG BOOK BUILDER</div>{!page.blocks.length&&<div className="empty">Add text, artwork, or a statblock from the right panel.</div>}{page.blocks.map(b=><article className={'block '+b.kind+(b.kind==='text'&&b.style?' '+b.style:'')} key={b.id}>{b.kind==='image'?(b.src?<img src={b.src} alt={b.alt} style={{objectFit:b.fit,opacity:b.opacity}}/>:<div className="imageDrop"><ImageIcon/> Drop artwork here</div>):<><input className="blockTitle" value={drafts[draftKey(b.id,'title')]??b.title} onChange={e=>draft(b.id,'title',e.target.value)} onBlur={()=>finishDraft(b.id,'title',b.title)}/>{b.kind==='text'&&<div className="textControls"><label>Style <select value={b.style??'body'} onChange={e=>replaceBlock(b.id,{style:e.target.value as 'body'|'heading'|'note'|'table'})}><option value="body">Body</option><option value="heading">Heading</option><option value="note">Note</option><option value="table">Table</option></select></label><label>Align <select value={b.align??'left'} onChange={e=>replaceBlock(b.id,{align:e.target.value as 'left'|'center'|'right'})}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label><label>Size <input type="number" min="10" max="36" value={b.fontSize??16} onChange={e=>replaceBlock(b.id,{fontSize:Number(e.target.value)})}/></label><label>Columns <select value={b.columns} onChange={e=>replaceBlock(b.id,{columns:Number(e.target.value) as 1|2})}><option value="1">1</option><option value="2">2</option></select></label></div>}<textarea className={b.kind==='text'&&b.columns===2?'twoColumns':''} style={b.kind==='text'?{textAlign:b.align??'left',fontSize:(b.fontSize??16)+'px'}:undefined} value={drafts[draftKey(b.id,'body')]??b.body} onChange={e=>draft(b.id,'body',e.target.value)} onBlur={()=>finishDraft(b.id,'body',b.body)}/></>}<div className="blockMove"><button title="Move block up" onClick={()=>moveBlock(b.id,-1)}><ArrowUp/></button><button title="Move block down" onClick={()=>moveBlock(b.id,1)}><ArrowDown/></button></div><button className="remove" title="Remove block" onClick={()=>change(p=>{const q=activePage(p);q.blocks=q.blocks.filter(x=>x.id!==b.id)})}><Trash2/></button></article>)}</div></main>
 <aside className="tools"><h3>Page</h3><label className="field">Size<select value={project.settings.pageSize} onChange={e=>change(p=>{p.settings.pageSize=e.target.value as 'letter'|'a4'})}><option value="letter">US Letter</option><option value="a4">A4</option></select></label><h3>Insert</h3><button onClick={()=>addTextStyle('body')}>Text block</button><button onClick={()=>addTextStyle('heading')}>Heading</button><button onClick={()=>addTextStyle('note')}>Sidebar / Note</button><button onClick={()=>addTextStyle('table')}>Table</button><button onClick={()=>imageRef.current?.click()}>Artwork</button><button onClick={()=>addStat('monster')}>Monster</button><button onClick={()=>addStat('npc')}>NPC</button><h3>Templates</h3>{(['spell','item','vehicle','trap','encounter','custom'] as StatblockKind[]).map(x=><button key={x} onClick={()=>addStat(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}<p className="hint">Projects autosave locally using the versioned project format. Save creates a portable .rpgbook file. Export PDF currently uses your system print dialog.</p></aside>
 <input hidden ref={fileRef} type="file" accept=".rpgbook,.json" onChange={e=>{load(e.target.files?.[0]);e.currentTarget.value=''}}/><input hidden ref={imageRef} type="file" accept="image/*" onChange={e=>{image(e.target.files?.[0]);e.currentTarget.value=''}}/></div>}
createRoot(document.getElementById('root')!).render(<App/>);
